## 주민등록상 거주인구
- 데이터 
    - 주민등록인구_20221223155840.xlsx
    - 서울특별시(구별)_18_19_20주민등록인구.csv

In [1]:
import pandas as pd
import numpy as np

In [2]:
resident_population = pd.read_excel("D:\MultiCampus\DATAexam\전공프로젝트\BigDataProject-AED-main\data\주민등록인구_20221223155840.xlsx")
resident_population.shape

C:\Users\sunfo\anaconda3\envs\data_venv\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

(27, 20)

In [3]:
display(resident_population.head())
display(resident_population.tail())

,동별(1),동별(2),2018,2018.1,2018.2,2018.3,2018.4,2018.5,2019,2019.1,2019.2,2019.3,2019.4,2019.5,2020,2020.1,2020.2,2020.3,2020.4,2020.5
0,동별(1),동별(2),세대 (세대),계,한국인,등록외국인,세대당인구,65세이상고령자,세대 (세대),계,한국인,등록외국인,세대당인구,65세이상고령자,세대 (세대),계,한국인,등록외국인,세대당인구,65세이상고령자
1,합계,소계,4263868.0,10049607.0,9765623.0,283984.0,2.29,1416131.0,4327605.0,10010983.0,9729107.0,281876.0,2.25,1485272.0,4417954.0,9911088.0,9668465.0,242623.0,2.19,1568331.0
2,NaN,종로구,73735.0,163026.0,153065.0,9961.0,2.08,26742.0,73947.0,161869.0,151290.0,10579.0,2.05,27519.0,75003.0,158996.0,149384.0,9612.0,1.99,28507.0
3,NaN,중구,61502.0,135633.0,125725.0,9908.0,2.04,22005.0,62739.0,136488.0,126171.0,10317.0,2.01,23275.0,63686.0,134635.0,125240.0,9395.0,1.97,24495.0
4,NaN,용산구,108974.0,245090.0,228999.0,16091.0,2.1,37640.0,110126.0,245185.0,228670.0,16515.0,2.08,38791.0,113093.0,244645.0,230040.0,14605.0,2.03,40247.0

,동별(1),동별(2),2018,2018.1,2018.2,2018.3,2018.4,2018.5,2019,2019.1,2019.2,2019.3,2019.4,2019.5,2020,2020.1,2020.2,2020.3,2020.4,2020.5
22,NaN,관악구,262222.0,520040.0,501957.0,18083.0,1.91,72249.0,268559.0,517334.0,500094.0,17240.0,1.86,75194.0,274811.0,509803.0,495060.0,14743.0,1.8,78875.0
23,NaN,서초구,172918.0,438163.0,433951.0,4212.0,2.51,54751.0,173199.0,435107.0,430826.0,4281.0,2.49,57136.0,173502.0,429025.0,425126.0,3899.0,2.45,60169.0
24,NaN,강남구,228775.0,547453.0,542364.0,5089.0,2.37,67085.0,232981.0,550209.0,545169.0,5040.0,2.34,71025.0,234872.0,544055.0,539231.0,4824.0,2.3,75096.0
25,NaN,송파구,270866.0,673507.0,666635.0,6872.0,2.46,81364.0,278711.0,682741.0,675961.0,6780.0,2.43,87334.0,281959.0,673926.0,667960.0,5966.0,2.37,93483.0
26,NaN,강동구,177247.0,431920.0,427573.0,4347.0,2.41,58770.0,183390.0,440390.0,436067.0,4323.0,2.38,63452.0,196499.0,463998.0,459970.0,4028.0,2.34,70019.0

In [4]:
resident_population.columns

Index(['동별(1)', '동별(2)', '2018', '2018.1', '2018.2', '2018.3', '2018.4',
       '2018.5', '2019', '2019.1', '2019.2', '2019.3', '2019.4', '2019.5',
       '2020', '2020.1', '2020.2', '2020.3', '2020.4', '2020.5'],
      dtype='object')

In [5]:
resident_population.drop(['동별(1)', '2018', '2018.2', '2018.3', '2018.4',
       '2018.5', '2019', '2019.2', '2019.3', '2019.4', '2019.5',
       '2020', '2020.2', '2020.3', '2020.4', '2020.5'], axis=1, inplace=True)
display(resident_population)

    동별(2)      2018.1      2019.1     2020.1
0   동별(2)           계           계          계
1      소계  10049607.0  10010983.0  9911088.0
2     종로구    163026.0    161869.0   158996.0
3      중구    135633.0    136488.0   134635.0
4     용산구    245090.0    245185.0   244645.0
5     성동구    316463.0    308979.0   300505.0
6     광진구    371063.0    366972.0   360109.0
7    동대문구    364338.0    363023.0   357014.0
8     중랑구    408147.0    402024.0   399562.0
9     성북구    447687.0    454744.0   447056.0
10    강북구    322915.0    317695.0   311569.0
11    도봉구    341649.0    335631.0   327361.0
12    노원구    548160.0    537303.0   527032.0
13    은평구    487666.0    484546.0   484043.0
14   서대문구    323080.0    323171.0   322952.0
15    마포구    386359.0    385925.0   381858.0
16    양천구    468145.0    462285.0   457781.0
17    강서구    603611.0    598273.0   585901.0
18    구로구    438486.0    439371.0   432488.0
19    금천구    254021.0    251820.0   247835.0
20   영등포구    403600.0    400986.0   407367.0
21    동작구    409385.0    408912.0   401572.0
22    관악구    520040.0    517334.0   509803.0
23    서초구    438163.0    435107.0   429025.0
24    강남구    547453.0    550209.0   544055.0
25    송파구    673507.0    682741.0   673926.0
26    강동구    431920.0    440390.0   463998.0

In [6]:
resident_population.rename(columns = {'동별(2)':'소재지','2018.1':'2018','2019.1':'2019','2020.1':'2020'},inplace=True)
resident_population

      소재지        2018        2019       2020
0   동별(2)           계           계          계
1      소계  10049607.0  10010983.0  9911088.0
2     종로구    163026.0    161869.0   158996.0
3      중구    135633.0    136488.0   134635.0
4     용산구    245090.0    245185.0   244645.0
5     성동구    316463.0    308979.0   300505.0
6     광진구    371063.0    366972.0   360109.0
7    동대문구    364338.0    363023.0   357014.0
8     중랑구    408147.0    402024.0   399562.0
9     성북구    447687.0    454744.0   447056.0
10    강북구    322915.0    317695.0   311569.0
11    도봉구    341649.0    335631.0   327361.0
12    노원구    548160.0    537303.0   527032.0
13    은평구    487666.0    484546.0   484043.0
14   서대문구    323080.0    323171.0   322952.0
15    마포구    386359.0    385925.0   381858.0
16    양천구    468145.0    462285.0   457781.0
17    강서구    603611.0    598273.0   585901.0
18    구로구    438486.0    439371.0   432488.0
19    금천구    254021.0    251820.0   247835.0
20   영등포구    403600.0    400986.0   407367.0
21    동작구    409385.0    408912.0   401572.0
22    관악구    520040.0    517334.0   509803.0
23    서초구    438163.0    435107.0   429025.0
24    강남구    547453.0    550209.0   544055.0
25    송파구    673507.0    682741.0   673926.0
26    강동구    431920.0    440390.0   463998.0

In [7]:
new_resident_population = resident_population.drop([0, 1], axis = 0)
new_resident_population

     소재지      2018      2019      2020
2    종로구  163026.0  161869.0  158996.0
3     중구  135633.0  136488.0  134635.0
4    용산구  245090.0  245185.0  244645.0
5    성동구  316463.0  308979.0  300505.0
6    광진구  371063.0  366972.0  360109.0
7   동대문구  364338.0  363023.0  357014.0
8    중랑구  408147.0  402024.0  399562.0
9    성북구  447687.0  454744.0  447056.0
10   강북구  322915.0  317695.0  311569.0
11   도봉구  341649.0  335631.0  327361.0
12   노원구  548160.0  537303.0  527032.0
13   은평구  487666.0  484546.0  484043.0
14  서대문구  323080.0  323171.0  322952.0
15   마포구  386359.0  385925.0  381858.0
16   양천구  468145.0  462285.0  457781.0
17   강서구  603611.0  598273.0  585901.0
18   구로구  438486.0  439371.0  432488.0
19   금천구  254021.0  251820.0  247835.0
20  영등포구  403600.0  400986.0  407367.0
21   동작구  409385.0  408912.0  401572.0
22   관악구  520040.0  517334.0  509803.0
23   서초구  438163.0  435107.0  429025.0
24   강남구  547453.0  550209.0  544055.0
25   송파구  673507.0  682741.0  673926.0
26   강동구  431920.0  440390.0  463998.0

In [8]:
new_resident_population = new_resident_population.reset_index()
display(new_resident_population)
new_resident_population.drop('index', axis=1, inplace=True)
new_resident_population

    index   소재지      2018      2019      2020
0       2   종로구  163026.0  161869.0  158996.0
1       3    중구  135633.0  136488.0  134635.0
2       4   용산구  245090.0  245185.0  244645.0
3       5   성동구  316463.0  308979.0  300505.0
4       6   광진구  371063.0  366972.0  360109.0
5       7  동대문구  364338.0  363023.0  357014.0
6       8   중랑구  408147.0  402024.0  399562.0
7       9   성북구  447687.0  454744.0  447056.0
8      10   강북구  322915.0  317695.0  311569.0
9      11   도봉구  341649.0  335631.0  327361.0
10     12   노원구  548160.0  537303.0  527032.0
11     13   은평구  487666.0  484546.0  484043.0
12     14  서대문구  323080.0  323171.0  322952.0
13     15   마포구  386359.0  385925.0  381858.0
14     16   양천구  468145.0  462285.0  457781.0
15     17   강서구  603611.0  598273.0  585901.0
16     18   구로구  438486.0  439371.0  432488.0
17     19   금천구  254021.0  251820.0  247835.0
18     20  영등포구  403600.0  400986.0  407367.0
19     21   동작구  409385.0  408912.0  401572.0
20     22   관악구  520040.0  517334.0  509803.0
21     23   서초구  438163.0  435107.0  429025.0
22     24   강남구  547453.0  550209.0  544055.0
23     25   송파구  673507.0  682741.0  673926.0
24     26   강동구  431920.0  440390.0  463998.0

     소재지      2018      2019      2020
0    종로구  163026.0  161869.0  158996.0
1     중구  135633.0  136488.0  134635.0
2    용산구  245090.0  245185.0  244645.0
3    성동구  316463.0  308979.0  300505.0
4    광진구  371063.0  366972.0  360109.0
5   동대문구  364338.0  363023.0  357014.0
6    중랑구  408147.0  402024.0  399562.0
7    성북구  447687.0  454744.0  447056.0
8    강북구  322915.0  317695.0  311569.0
9    도봉구  341649.0  335631.0  327361.0
10   노원구  548160.0  537303.0  527032.0
11   은평구  487666.0  484546.0  484043.0
12  서대문구  323080.0  323171.0  322952.0
13   마포구  386359.0  385925.0  381858.0
14   양천구  468145.0  462285.0  457781.0
15   강서구  603611.0  598273.0  585901.0
16   구로구  438486.0  439371.0  432488.0
17   금천구  254021.0  251820.0  247835.0
18  영등포구  403600.0  400986.0  407367.0
19   동작구  409385.0  408912.0  401572.0
20   관악구  520040.0  517334.0  509803.0
21   서초구  438163.0  435107.0  429025.0
22   강남구  547453.0  550209.0  544055.0
23   송파구  673507.0  682741.0  673926.0
24   강동구  431920.0  440390.0  463998.0

In [9]:
new_resident_population['구별 거주인구 평균']=new_resident_population[['2018','2019','2020']].mean(axis=1)

In [10]:
new_resident_population

     소재지      2018      2019      2020     구별 거주인구 평균
0    종로구  163026.0  161869.0  158996.0  161297.000000
1     중구  135633.0  136488.0  134635.0  135585.333333
2    용산구  245090.0  245185.0  244645.0  244973.333333
3    성동구  316463.0  308979.0  300505.0  308649.000000
4    광진구  371063.0  366972.0  360109.0  366048.000000
5   동대문구  364338.0  363023.0  357014.0  361458.333333
6    중랑구  408147.0  402024.0  399562.0  403244.333333
7    성북구  447687.0  454744.0  447056.0  449829.000000
8    강북구  322915.0  317695.0  311569.0  317393.000000
9    도봉구  341649.0  335631.0  327361.0  334880.333333
10   노원구  548160.0  537303.0  527032.0  537498.333333
11   은평구  487666.0  484546.0  484043.0  485418.333333
12  서대문구  323080.0  323171.0  322952.0  323067.666667
13   마포구  386359.0  385925.0  381858.0  384714.000000
14   양천구  468145.0  462285.0  457781.0  462737.000000
15   강서구  603611.0  598273.0  585901.0  595928.333333
16   구로구  438486.0  439371.0  432488.0  436781.666667
17   금천구  254021.0  251820.0  247835.0  251225.333333
18  영등포구  403600.0  400986.0  407367.0  403984.333333
19   동작구  409385.0  408912.0  401572.0  406623.000000
20   관악구  520040.0  517334.0  509803.0  515725.666667
21   서초구  438163.0  435107.0  429025.0  434098.333333
22   강남구  547453.0  550209.0  544055.0  547239.000000
23   송파구  673507.0  682741.0  673926.0  676724.666667
24   강동구  431920.0  440390.0  463998.0  445436.000000

In [11]:
# 저장 후 주석처리
# new_resident_population.to_csv("D:\MultiCampus\DATAexam\전공프로젝트\BigDataProject-AED-main\data\서울특별시(구별)_18_19_20주민등록인구.csv", index=False, encoding='utf-8-sig')